FROM ubuntu:18.04

# Update apt-get
RUN apt-get update -y

# Setup tools
RUN apt-get install git wget unzip build-essential libffi-dev python3 python3-dev python3-pip libfuzzy-dev -y

# Setup pehash
WORKDIR /install-pehash
RUN git clone https://github.com/knowmalware/pehash \
    && cd pehash \
    && python3 setup.py install

# Setup PEiD
WORKDIR /root/web-PEanalysis/PEiD
RUN wget https://github.com/K-atc/PEiD/releases/download/v0.1.1/PEiD \
    && chmod 755 PEiD \
    && ./PEiD --prepare

# Setup trid
WORKDIR /root/web-PEanalysis/trid
RUN wget http://mark0.net/download/trid_linux_64.zip \
    && unzip trid_linux_64.zip \
    && chmod 755 trid
RUN wget http://mark0.net/download/tridupdate.zip \
    && unzip tridupdate.zip \
    && python3 tridupdate.py

# Setup winchecksec
WORKDIR /root/web-PEanalysis/winchecksec
RUN wget https://github.com/trailofbits/winchecksec/releases/download/v2.0.0/ubuntu-latest.Release.zip \
    && unzip ubuntu-latest.Release.zip \
    && chmod 755 build/winchecksec


# Setup web-PEanalysis
WORKDIR /root/web-PEanalysis
RUN pip3 install --no-cache-dir ssdeep pyimpfuzzy pefile Flask pymongo virustotal-api 
COPY . .

CMD [ "python3", "./app.py"  ]
